### ISSUE TITLE
AttributeError: 'PosixPath' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by jarcoal** [joke2k/faker#1444]
* Faker version: 8.1.3 and 8.1.4
* OS: MacOS 11.2.3

After updating from 8.1.2 -> 8.1.3 I'm seeing the following exception:

```
AttributeError: 'PosixPath' object has no attribute 'startswith'
```

I'm guessing that it's related to this commit: https://github.com/joke2k/faker/commit/c440ac1d742dd26fe771e8a3de2b0453d279dde4

**Comment by fcurella** [comment]
Thanks for the report @jarcoal! Could you paste the full stacktrace?

**Comment by jarcoal** [comment]
And just like that, I can't repro it. ✨  🎩 

Closing and will re-open if I encounter it again.  Thanks for your quick reply @fcurella .

**Comment by lukaszbanasiak** [comment]
I have the same issue when running tests in Github Actions, therefore I have access to traceback.

```python
(...)
  File "/home/runner/work/talar-app/talar-app/app/payments/tests/factories.py", line 1, in <module>
    from factory import DjangoModelFactory, SelfAttribute, SubFactory
  File "/home/runner/.cache/pypoetry/virtualenvs/talar-app-hAqRCjVK-py3.8/lib/python3.8/site-packages/factory/__init__.py", line 26, in <module>
    from .faker import Faker
  File "/home/runner/.cache/pypoetry/virtualenvs/talar-app-hAqRCjVK-py3.8/lib/python3.8/site-packages/factory/faker.py", line 22, in <module>
    import faker
  File "/home/runner/.cache/pypoetry/virtualenvs/talar-app-hAqRCjVK-py3.8/lib/python3.8/site-packages/faker/__init__.py", line 1, in <module>
    from faker.factory import Factory
  File "/home/runner/.cache/pypoetry/virtualenvs/talar-app-hAqRCjVK-py3.8/lib/python3.8/site-packages/faker/factory.py", line 7, in <module>
    from faker.config import AVAILABLE_LOCALES, DEFAULT_LOCALE, PROVIDERS
  File "/home/runner/.cache/pypoetry/virtualenvs/talar-app-hAqRCjVK-py3.8/lib/python3.8/site-packages/faker/config.py", line 11, in <module>
    PROVIDERS = find_available_providers(
  File "/home/runner/.cache/pypoetry/virtualenvs/talar-app-hAqRCjVK-py3.8/lib/python3.8/site-packages/faker/utils/loading.py", line 57, in find_available_providers
    for mod in list_module(providers_mod) if mod != '__pycache__'
  File "/home/runner/.cache/pypoetry/virtualenvs/talar-app-hAqRCjVK-py3.8/lib/python3.8/site-packages/faker/utils/loading.py", line 35, in list_module
    return [name for _, name, is_pkg in pkgutil.iter_modules([path]) if is_pkg]
  File "/home/runner/.cache/pypoetry/virtualenvs/talar-app-hAqRCjVK-py3.8/lib/python3.8/site-packages/faker/utils/loading.py", line 35, in <listcomp>
    return [name for _, name, is_pkg in pkgutil.iter_modules([path]) if is_pkg]
  File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/pkgutil.py", line 129, in iter_modules
    for i in importers:
  File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/pkgutil.py", line 419, in get_importer
    importer = path_hook(path_item)
  File "<frozen importlib._bootstrap_external>", line 1594, in path_hook_for_FileFinder
  File "<frozen importlib._bootstrap_external>", line 1469, in __init__
  File "<frozen importlib._bootstrap_external>", line 177, in _path_isabs
AttributeError: 'PosixPath' object has no attribute 'startswith'
```

**Comment by fcurella** [comment]
@lukaszbanasiak This bug fixed in v8.1.3. Looks like you're using an older version

**Comment by lukaszbanasiak** [comment]
Exactly. I'm using `factory_boy` and depends on `faker`. A new version of `factory_boy` is not updating `faker` but I managed this myself and it's now working fine. Thanks.
