### ISSUE TITLE
Version 15.1.0 not working in python 3.7

### ISSUE THREAD

**Issue by jakobdo** [joke2k/faker#1732]
* Faker version: 15.1.0
* OS: Windows
* Python: 3.7

Brief summary of the issue goes here.

When importing Faker 15.1.0, it raises an exception:

In this line:
faker/providers/__init__.py
from typing import Any, Collection, List, Optional, OrderedDict, Sequence, TypeVar, Union
ImportError: cannot import name 'OrderedDict' from 'typing'

### Steps to reproduce

1. Install python 3.7
1. from typing import OrderedDict
1. it should raise an exception.

### Expected behavior

I would expect faker to be imported and working as expected.

### Actual behavior

ImportError: cannot import name 'OrderedDict' from 'typing'

**Comment by stefan6419846** [comment]
Which version of `typing_extensions` do you have? It seems like at least version 3.10.0.1 is required (https://github.com/python/typing_extensions/commit/b22e66916ed26e4705fa3359fda4b5a5d1af7128, as the change for 3.10.0.0 in https://github.com/python/typing_extensions/commit/c7194ebb1cb849b571332e568742ee25197dbbeb had been flawed).
